#!/bin/sh

# Important
## Whenever you clone your repository with git hooks you need to enable git hooks once again
## `git config core.hooksPath .git-hooks`

# fix for windows systems
PATH="/c/Program Files/nodejs:$HOME/AppData/Roaming/npm/:$PATH"

npx git-conventional-commits commit-msg-hook "$1"
